spring:
  cloud:
    config:
      enabled: false
      server:
        native:
          search-locations: classpath:/service
  profiles:
     active: native

security:
  user:
    name: ${CONFIGURATION_SERVICE_USERNAME}
    password: ${CONFIGURATION_SERVICE_PASSWORD}
  ignored:
    - /health
logging:
 level.: ERROR

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false