logging:
  level:
    root: ERROR
server:
  error:
    whitelabel:
      enabled: false
  tomcat:
    max-http-post-size: 20971520
endpoints:
  jmx:
    enabled: false
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000